name: Build

on: [push]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/altinn-rettigheter-proxy-klient:${{ github.sha }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run clean install (med tests)
        run: mvn clean install
